### PR TITLE
Sphere scaling

### PR DESCRIPTION
**Pull request by megalodonatron**
Checking in slider and functionality for sphere scaling, resolving [issue 3](https://github.com/qiime/evident/issues/3)

### CODE REVIEW

**Comment by ElDeveloper** [comment]
Oh, ok thought you added it on this commit.

This functionality works like charm! :jack_o_lantern: 

:+1:

**Comment by megalodonatron** [comment]
How many upvotes are we requiring before something is merged? Can we :+1: ourselves?

**Comment by ElDeveloper** [comment]
Don't know about that @antgonza, @wdwvt1?

Also noticed, the step size of the slider is 0.2, I think a smaller value would make the transition smoother? Maybe 0.05?

**Comment by megalodonatron** [comment]
That's possible but then it would make it harder to get back to a whole number step like 1.

**Comment by ElDeveloper** [comment]
Makes a lot of sense.

**Comment by antgonza** [comment]
I think that as long one other person reviews the code and test it, we are good to go.

**Pull request merged**
